# Date constants
AUGUST_MONTH = 8
OCTOBER_MONTH = 10
APRIL_MONTH = 4
MONTH_1ST = 1
MONTH_30TH = 30
TWO_WEEKS_NUM_DAYS = 14

# Game information constants
AWAY = "away"
HOME = "home"
NUM_PERIODS = 3
PERIOD_LENGTH_MINUTES = 20
OVERTIME_LENGTH_MINUTES = 5
MINUTE_INCREMENTS = 1
PENALTY_LENGTH_MINUTES = 2
NUM_GAMES_IN_SEASON = 82

# Percentage constants
SHOOTOUT_WINNER_PERCENTAGE = 0.5
PENALTY_CHANCE_PERCENTAGE = 0.13
PLAYOFF_PENALTY_CHANCE_PERCENTAGE = 0.08
UNASSITED_GOAL_PERCENTAGE = 0.10
SINGLE_ASSISTED_GOAL_PERCENTAGE = 0.4

# Lineup constants
LINEUP1_NUMBER = 1
LINEUP2_NUMBER = 2
LINEUP3_NUMBER = 3
LINEUP4_NUMBER = 4

# API or calculation constants
VALID_STATS_MIN_GAMES = 10
REGULAR_SEASON_VALUE = 2
