# Date constants
SEPTEMBER_MONTH = 9
TWO_WEEKS_NUM_DAYS = 14

# Game information constants
AWAY = "away"
HOME = "home"
NUM_PERIODS = 3
PERIOD_LENGTH_MINUTES = 20
OVERTIME_LENGTH_MINUTES = 5
MINUTE_INCREMENTS = 1
PENALTY_LENGTH_MINUTES = 2
NUM_GAMES_IN_SEASON = 82

# Percentage constants
SHOOTOUT_WINNER_PERCENTAGE = 0.5
PENALTY_CHANCE_PERCENTAGE = 0.15
UNASSITED_GOAL_PERCENTAGE = 0.05
SINGLE_ASSISTED_GOAL_PERCENTAGE = 0.3

# Lineup constants
LINEUP1_NUMBER = 1
LINEUP2_NUMBER = 2
LINEUP3_NUMBER = 3
LINEUP4_NUMBER = 4

# API or calculation constants
VALID_STATS_MIN_GAMES = 10
REGULAR_SEASON_VALUE = 2
